version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: snowflake_customer_puchases
    description: "The total purchase value for each customer in snowflake sample data"
    columns:
      - name: cust_key
        description: "Customer key"
        tests:
          - unique
          - not_null

  - name: cumulative_orders_by_date
    description: "The cumulative value of sales across time"
    columes:
      - name: data
        description: "Date of cumulation"
        tests:
          - unique
          - not_null
      - name: cum_sales
        description: "Total sales so far"
        tests:
          - not_null
