version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - accepted_values:
              values: [1, 2]
              quote: False

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - relationships:
              to: ref('my_first_dbt_model')
              field: id

  - name: snowflake_customer_puchases
    description: "The total purchase value for each customer in snowflake sample data"
    columns:
      - name: cust_key
        description: "Customer key"
        tests:
          - unique
          - not_null

  - name: cumulative_orders_by_date
    description: "The cumulative value of sales across time"
    columes:
      - name: data
        description: "Date of cumulation"
        tests:
          - unique
          - not_null
      - name: cum_sales
        description: "Total sales so far"
        tests:
          - not_null

  - name: dates

  - name: incremental_time
    description: "Table of seconds that has passed so far today"
    columns:
      - name: time
        description: "Timestamp in datetime format"
        tests:
          - unique
          - not_null

  - name: playing_with_tests
    description: "Model to run tests on"
    columns:
      - name: c_custkey
        description: "Customer key"
        tests:
          - unique
          - not_null
      - name: c_mktsegment
        description: "Market segment"
        tests:
          - accepted_values:
              values:
                [
                  "BUILDING",
                  "AUTOMOBILE",
                  "MACHINERY",
                  "HOUSEHOLD",
                  "FURNITURE",
                ]
